{{"OpenChest"," - Кейсики"}, "http://pastebin.com/raw/QTCJZq3c",{"internet","chat_box"}},
{{"AncientEmerald MOD"," - Халявные эмы"}, "https://pastebin.com/raw/bGPdFqvr",{"internet"}},
{{"OpenAdmins"," - Мод состав"},"http://pastebin.com/raw/xN5AFT0u",{"internet","opencb"}},
{{"OpenInfo"," - Инфо панель"},"http://pastebin.com/raw/teGcGxXE",{"internet"}},
{{"OpenBc"," - Объявления (A: Shyvana)"},"http://pastebin.com/raw/GtPthhpm",{"internet", "chat_box"}},
{{"OpenRep"," - Сис-ма рейтингов"},"http://pastebin.com/raw/E0ih3kP6",{"internet", "chat_box", "opencb"}},
{{"Bankomat"," - банк"},"http://pastebin.com/raw/t3yvmr68",{"internet", "opencb"}},
{{"UChat"," - чат избранных (A: InfinityDark)"},"",{"Недоступен"}},
{{"Holograms"," - голограммы"},"https://raw.githubusercontent.com/BarawikS/Holo/master/holograms/holo_print.lua",{"internet", "chat_box"}},
{{"Bankomat MOD"," - банк"},"http://pastebin.com/raw/yTfthrA2",{"internet"}}